### PR TITLE
Multirotor mixers 6dof

### PR DESCRIPTION
**Pull request by jlecoeur**

### CODE REVIEW

**Comment by jlecoeur** [comment]
Short video demonstrating "Go to location". Missions also work.
[short video](https://youtu.be/OCzCjDPJVAs)

**Comment by Jaeyoung-Lim** [comment]
What is the status of this PR? I am very intrested on building a airframe for it!

**Comment by jlecoeur** [comment]
@Jaeyoung-Lim very outdated !

Hopefully https://github.com/PX4/Firmware/pull/13351 and https://github.com/PX4/Firmware/pull/13519 will make it soon into master.
Then, the only thing left to port will the changes made in the MC position controller (https://github.com/jlecoeur/Firmware/pull/1/commits/1690ec36be012693c9859247df16e13c42752d84).

:crossed_fingers: 

FYI @RomanBapst @Bresch @dagar

**Comment by Jaeyoung-Lim** [comment]
@Jaeyoung-Lim Pretty awesome! Do you think it would make sense to add 3d force setpoint support for MC position / attitude controller? or do we need a separate Omnicopter attitude controller?

**Comment by jlecoeur** [comment]
Now that we have the work queues, it is relatively cheap to separate processing steps into modules.

What would make sense IMO would be to *always* provide 3D force setpoint in the position controller, then have different "mapping" modules convert it to attitude + 3D thrust based on the current airframe.
- for multirotors, it would provide attitude setpoint just like now + a thrust setpoint aligned with the Z body axis
- for omnicopters and VTOL, it would provide attitude + 3D thrust
- for fixed wing, we can also think of converting the 3D force setpoint into attitude and forward thrust

**Comment by Jaeyoung-Lim** [comment]
@jlecoeur Thanks for the insights! I would be really excited to see fully actuated systems being enabled

**Pull request closed without merging**
